#include <iostream>

#include "database.hpp"
#include "page_data.hpp"

using std::cout;
using std::endl;

int main(void)
{
    database my_database("test_db");
    struct page_data_s* my_page = new struct page_data_s;

    std::string test_url = "http://test_url.com/a_test_page.html";

    //create test data
    my_page->rank = 42;
    my_page->meta = {"some", "keywords", "for", "testing"};
    my_page->description = "multiline description for\ntest page generated by test_database.cpp";
    my_page->last_visit = 12;
    my_page->crawl_delay = 5;

    cout<<"sending to database.."<<endl;
    my_database.put_page_data(my_page, test_url);

    //flush page
    delete my_page;
    my_page = new struct page_data_s;

    cout<<"reading from database.."<<endl;
    my_database.get_page_data(my_page, test_url);
    
    cout<<"page rank: "<<my_page->rank<<endl;
    cout<<"meta: "<<endl;
    for(auto& x: my_page->meta)
        cout<<"\t"<<x<<endl;

    cout<<"description: "<<my_page->description;
    cout<<"last visit: "<<my_page->last_visit<<endl;
    cout<<"crawl delay: "<<my_page->crawl_delay<<endl;
    
    cout<<"~~~\ndone!"<<endl;
    delete my_page;
    return 0;
}
