#include <iostream>

#include "database.hpp"
#include "page_data.hpp"

using std::cout;
using std::endl;

int main(void)
{
    database my_database("test_db");
    struct page_data_s* my_page;

    std::string test_url = "http://test_url.com/a_test_page.html";

    //allocate a new page
    cout<<"creating new page"<<endl;
    my_page = my_database.get_page(test_url);

    //create test data
    my_page->rank = 42;
    my_page->meta = {"some", "keywords", "for", "testing"};
    my_page->description = "test page generated by test_database.cpp";
    my_page->last_visit = 12345678;
    my_page->crawl_delay = 5;

    //write to database
    cout<<"sending to database"<<endl;
    my_database.put_page(test_url, my_page);

    cout<<"~~~\ndone!"<<endl;
    delete my_page;
    return 0;
}
